version: 2

sources:
  - name: pagila_src
    schema: public

    tables:
      - name: actor
      - name: address
      - name: category
      - name: city
      - name: country
      - name: customer
      - name: film
      - name: film_actor
      - name: film_category
      - name: inventory
      - name: language
      - name: payment
      - name: payment_p2007_01
      - name: payment_p2007_02
      - name: payment_p2007_03
      - name: payment_p2007_04
      - name: payment_p2007_05
      - name: payment_p2007_06
      - name: rental
      - name: staff
      - name: store


models:
  - name: actor
    description: Source table containing actor information.

    config:
      contract:
        enforced: true

    columns:
      - name: actor_id
        description: '{{doc("actor_id")}}'
        data_type: smallint
        tests:
          - not_null
          - unique

      - name: first_name
        description: '{{doc("first_name")}}'
        data_type: varchar

      - name: last_name
        description: '{{doc("last_name")}}'
        data_type: varchar

      - name: last_update
        description: '{{doc("last_update")}}'
        data_type: timestamp without time zone
  

  - name: customer
    description: Source table containing customer information.

    config:
      contract:
        enforced: true

    columns:
      - name: customer_id
        description: '{{doc("customer_id")}}'
        data_type: smallint
        tests:
          - not_null
          - unique

      - name: store_id
        description: '{{doc("store_id")}}'
        data_type: smallint

      - name: first_name
        description: '{{doc("first_name")}}'
        data_type: varchar

      - name: last_name
        description: '{{doc("last_name")}}'
        data_type: varchar

      - name: email
        description: '{{doc("email")}}'
        data_type: varchar

      - name: address_id
        description: '{{doc("address_id")}}'
        data_type: smallint

      - name: activebool
        description: '{{doc("activebool")}}'
        data_type: boolean

      - name: create_date
        description: '{{doc("create_date")}}'
        data_type: timestamp without time zone

      - name: last_update
        description: '{{doc("last_update")}}'
        data_type: timestamp without time zone

      - name: active
        description: '{{doc("active")}}'
        data_type: smallint
