version: 2

sources:
  - name: pagila
    schema: public

    tables:
      - name: actor
        description: Source table containing actor information.
        columns:
          - name: actor_id
            description: '{{doc("actor_id")}}'
            data_type: smallint

          - name: first_name
            description: '{{doc("first_name")}}'
            data_type: varchar

          - name: last_name
            description: '{{doc("last_name")}}'
            data_type: varchar

          - name: last_update
            description: '{{doc("last_update")}}'
            data_type: timestamp without time zone
      - name: address
      - name: category
      - name: city
      - name: country
      - name: customer
      - name: film
      - name: film_actor
      - name: film_category
      - name: inventory
      - name: language
      - name: payment
      - name: payment_p2007_01
      - name: payment_p2007_02
      - name: payment_p2007_03
      - name: payment_p2007_04
      - name: payment_p2007_05
      - name: payment_p2007_06
      - name: rental
      - name: staff
      - name: store